### INSTALACIONES E IMPORTACIONES

In [1]:
pip install pyedflib #Recomendado para ver eeg en python

Note: you may need to restart the kernel to use updated packages.

ERROR: Invalid requirement: '#Recomendado'

[notice] A new release of pip available: 22.2.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
pip install pandas

Requirement already satisfied: pandas in c:\users\yamal\onedrive\escritorio\proyectos en github\fractals-dimension-eeg\env\lib\site-packages (2.3.1)
Requirement already satisfied: pytz>=2020.1 in c:\users\yamal\onedrive\escritorio\proyectos en github\fractals-dimension-eeg\env\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\yamal\onedrive\escritorio\proyectos en github\fractals-dimension-eeg\env\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: numpy>=1.22.4 in c:\users\yamal\onedrive\escritorio\proyectos en github\fractals-dimension-eeg\env\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: tzdata>=2022.7 in c:\users\yamal\onedrive\escritorio\proyectos en github\fractals-dimension-eeg\env\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\yamal\onedrive\escritorio\proyectos en github\fractals-dimension-eeg\env\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.2.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd

In [4]:
import pyedflib

In [5]:
import mne

In [6]:
import pooch

In [7]:
import numpy as np
import matplotlib.pyplot as plt

In [8]:
import antropy as ant

In [9]:
import matplotlib.pyplot as plt

In [10]:
import zipfile

In [11]:
import os

In [12]:
import pathlib

In [53]:
from scipy.stats import mannwhitneyu

En esta pagina https://physionet.org/content/eegmat/1.0.0/ vamos a encontrar eeg realizado a un grupo de sujetos
en modo reposo y durante la resolución de ejercicios matemáticos. Uno por uno analizaremos la dimensión fractal de cada área del cerebro. Luego crearemos df para comparar las variaciones en general de todos los sujetos según áreas del cerebro. Tenemos sujeto00_01 es el sujeto 00 en estado reposo y sujeto00_02 el mismo pero resolviendo ejercicios matematicos.

Hay 21 canales EEG (Fp1, Fp2, F3, F4, etc.).
La frecuencia de muestreo es 500 Hz (500 puntos por segundo por canal).
Está filtrado de 0.5 Hz a 45 Hz.
El registro dura ~182 segundos (~3 minutos).

Frontal: Fp1, Fp2, F3, F4, F7, F8
Temporal: T3, T4, T5, T6
Parietal: P3, P4, Pz
Occipital: O1, O2
Central: C3, C4, Cz

### Calculo DM por tramo entero de los primeros 9 sujetos

In [13]:
url = "https://physionet.org/static/published-projects/eegmat/1.0.0/Subject00_1.edf"

# Descargar temporalmente
path = pooch.retrieve(
    url=url,
    known_hash=None  # No verificamos hash para agilizar
)

# Abrir con MNE
raw = mne.io.read_raw_edf(path, preload=True)
print(raw.info)

Extracting EDF parameters from C:\Users\yamal\AppData\Local\pooch\pooch\Cache\53c52e9eb313b49f18dcacb950744ce1-Subject00_1.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 90999  =      0.000 ...   181.998 secs...
<Info | 8 non-empty values
 bads: []
 ch_names: EEG Fp1, EEG Fp2, EEG F3, EEG F4, EEG F7, EEG F8, EEG T3, EEG ...
 chs: 21 EEG
 custom_ref_applied: False
 highpass: 0.5 Hz
 lowpass: 45.0 Hz
 meas_date: 2011-01-01 00:00:00 UTC
 nchan: 21
 projs: []
 sfreq: 500.0 Hz
 subject_info: <subject_info | his_id: 0, sex: 1, last_name: Subject0, birthday: 1990-01-01>
>

In [14]:

# Archivo donde guardaremos todo
csv_file = "resultados_fractales.csv"

# Lista de sujetos (puedes ajustar el rango)
sujetos = [f"Subject{i:02d}" for i in range(10)]  # 00 a 09

# Lista para acumular resultados
resultados = []

for sujeto in sujetos:
    for estado in [1, 2]:  # 1 = reposo, 2 = actividad
        condicion = "reposo" if estado == 1 else "actividad"
        
        # URL EDF
        url = f"https://physionet.org/static/published-projects/eegmat/1.0.0/{sujeto}_{estado}.edf"
        print(f"Procesando: {sujeto} - {condicion}")

        # Descargar
        path = pooch.retrieve(url=url, known_hash=None)

        # Leer EDF
        raw = mne.io.read_raw_edf(path, preload=True)
        data, _ = raw.get_data(return_times=True)
        canales = raw.ch_names

        # Calcular Higuchi FD para cada canal
        for i, canal in enumerate(canales):
            valor_fd = ant.higuchi_fd(data[i], kmax=10)
            resultados.append({
                "sujeto": sujeto[-2:],      # "00", "01", ...
                "condicion": condicion,     # "reposo" o "actividad"
                "canal": canal,             # Nombre del canal
                "valor_fractal": valor_fd   # FD calculada
            })

# Crear DataFrame long
df_long = pd.DataFrame(resultados)

# Guardar CSV
df_long.to_csv(csv_file, index=False)

print("\n✅ Listo. Archivo guardado en:", csv_file)
print(df_long.head())

Procesando: Subject00 - reposo
Extracting EDF parameters from C:\Users\yamal\AppData\Local\pooch\pooch\Cache\53c52e9eb313b49f18dcacb950744ce1-Subject00_1.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 90999  =      0.000 ...   181.998 secs...
Procesando: Subject00 - actividad
Extracting EDF parameters from C:\Users\yamal\AppData\Local\pooch\pooch\Cache\497838b58060f20164e2cf29584f519f-Subject00_2.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 30999  =      0.000 ...    61.998 secs...
Procesando: Subject01 - reposo
Extracting EDF parameters from C:\Users\yamal\AppData\Local\pooch\pooch\Cache\6f1180d28763a7ade30931f2400ef8cd-Subject01_1.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 90999  =      0.000 ...   181.998 secs...
Procesando: Subject01 - actividad
Extracting EDF parameters from C:\Users\yamal\AppData\Local\pooch\pooch\Cache\cb8fe0acaf4f8e6ef794a338a9e74124-Subject01_2.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 30999  =      0.000 ...    61.998 secs...
Procesando: Subject02 - reposo
Extracting EDF parameters from C:\Users\yamal\AppData\Local\pooch\pooch\Cache\e714bc02df80f1d861a36fe1df364a60-Subject02_1.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 90999  =      0.000 ...   181.998 secs...
Procesando: Subject02 - actividad
Extracting EDF parameters from C:\Users\yamal\AppData\Local\pooch\pooch\Cache\841e87a3abf6a859e5627f47f0440789-Subject02_2.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 30999  =      0.000 ...    61.998 secs...
Procesando: Subject03 - reposo
Extracting EDF parameters from C:\Users\yamal\AppData\Local\pooch\pooch\Cache\335974bc4cb8ee49803d307acda796fc-Subject03_1.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 90999  =      0.000 ...   181.998 secs...
Procesando: Subject03 - actividad
Extracting EDF parameters from C:\Users\yamal\AppData\Local\pooch\pooch\Cache\874362f8c3f3eb4460ac871c0815a585-Subject03_2.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 30999  =      0.000 ...    61.998 secs...
Procesando: Subject04 - reposo
Extracting EDF parameters from C:\Users\yamal\AppData\Local\pooch\pooch\Cache\ca342445469ebcee1b3367e5b49985c7-Subject04_1.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 84999  =      0.000 ...   169.998 secs...
Procesando: Subject04 - actividad
Extracting EDF parameters from C:\Users\yamal\AppData\Local\pooch\pooch\Cache\f6fc59fdbee04f733a1154bced49b057-Subject04_2.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 30999  =      0.000 ...    61.998 secs...
Procesando: Subject05 - reposo
Extracting EDF parameters from C:\Users\yamal\AppData\Local\pooch\pooch\Cache\ac909dffad536386e830da9c910285d1-Subject05_1.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 90999  =      0.000 ...   181.998 secs...
Procesando: Subject05 - actividad
Extracting EDF parameters from C:\Users\yamal\AppData\Local\pooch\pooch\Cache\c0e13120f763d8c6303075ab55d76eb5-Subject05_2.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 30999  =      0.000 ...    61.998 secs...
Procesando: Subject06 - reposo
Extracting EDF parameters from C:\Users\yamal\AppData\Local\pooch\pooch\Cache\6d4b048b70f45bdf0f596224e3b1bae3-Subject06_1.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 90999  =      0.000 ...   181.998 secs...
Procesando: Subject06 - actividad
Extracting EDF parameters from C:\Users\yamal\AppData\Local\pooch\pooch\Cache\d827ceadc36da982d1f0519ff73ef6df-Subject06_2.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 30999  =      0.000 ...    61.998 secs...
Procesando: Subject07 - reposo
Extracting EDF parameters from C:\Users\yamal\AppData\Local\pooch\pooch\Cache\cb66941da42194d1083159d4400f2739-Subject07_1.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 90999  =      0.000 ...   181.998 secs...
Procesando: Subject07 - actividad
Extracting EDF parameters from C:\Users\yamal\AppData\Local\pooch\pooch\Cache\cc501b270f0db32e66643c74e3167cf8-Subject07_2.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 30999  =      0.000 ...    61.998 secs...
Procesando: Subject08 - reposo
Extracting EDF parameters from C:\Users\yamal\AppData\Local\pooch\pooch\Cache\3f4416cb2dabd0de1fd4f0583fba0bf7-Subject08_1.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 90999  =      0.000 ...   181.998 secs...
Procesando: Subject08 - actividad
Extracting EDF parameters from C:\Users\yamal\AppData\Local\pooch\pooch\Cache\4c9e96ff48b1c2255b197a89c8d257ad-Subject08_2.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 30999  =      0.000 ...    61.998 secs...
Procesando: Subject09 - reposo
Extracting EDF parameters from C:\Users\yamal\AppData\Local\pooch\pooch\Cache\b45a8069aa72207465ce53ed46207a19-Subject09_1.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 90999  =      0.000 ...   181.998 secs...
Procesando: Subject09 - actividad
Extracting EDF parameters from C:\Users\yamal\AppData\Local\pooch\pooch\Cache\ae68925cf6ca349cb0b2ad6ea4fbdd70-Subject09_2.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 30999  =      0.000 ...    61.998 secs...

✅ Listo. Archivo guardado en: resultados_fractales.csv
  sujeto condicion    canal  valor_fractal
0     00    reposo  EEG Fp1       1.102250
1     00    reposo  EEG Fp2       1.119314
2     00    reposo   EEG F3       1.101865
3     00    reposo   EEG F4       1.097340
4     00    reposo   EEG F7       1.124143

In [15]:
df_long.head()

  sujeto condicion    canal  valor_fractal
0     00    reposo  EEG Fp1       1.102250
1     00    reposo  EEG Fp2       1.119314
2     00    reposo   EEG F3       1.101865
3     00    reposo   EEG F4       1.097340
4     00    reposo   EEG F7       1.124143

In [16]:
# Convertir de formato long a wide por sujeto y canal
df_var = df_long.pivot_table(
    index=["sujeto", "canal"],     # cada combinación de sujeto y canal es una fila
    columns="condicion",           # columnas separadas: reposo, actividad
    values="valor_fractal",
    aggfunc="first"                # usamos 'first' porque no hay duplicados
).reset_index()

# Calcular variación
df_var["variacion"] = df_var["actividad"] - df_var["reposo"]

In [17]:
df_var.head()

condicion sujeto      canal  actividad    reposo  variacion
0             00    ECG ECG   1.073343  1.059201   0.014142
1             00  EEG A2-A1   1.159064  1.083710   0.075354
2             00     EEG C3   1.109658  1.103591   0.006068
3             00     EEG C4   1.107483  1.101031   0.006452
4             00     EEG Cz   1.103878  1.099786   0.004093

In [18]:
df_var.nlargest(10, "variacion", keep="all")

condicion sujeto      canal  actividad    reposo  variacion
145           06     EEG T5   1.283424  1.168686   0.114738
141           06     EEG P4   1.209026  1.103526   0.105500
144           06     EEG T4   1.203839  1.109055   0.094784
142           06     EEG Pz   1.210310  1.117937   0.092372
140           06     EEG P3   1.230099  1.140035   0.090064
21            01    ECG ECG   1.240052  1.150989   0.089063
146           06     EEG T6   1.191778  1.104541   0.087236
106           05  EEG A2-A1   1.203858  1.118286   0.085572
143           06     EEG T3   1.222456  1.136941   0.085515
129           06     EEG C4   1.198444  1.114210   0.084233

In [19]:
df_var.nsmallest(10, "variacion", keep="all")

condicion sujeto      canal  actividad    reposo  variacion
169           08  EEG A2-A1   1.105634  1.178122  -0.072488
84            04    ECG ECG   1.104135  1.160495  -0.056360
42            02    ECG ECG   1.198266  1.246566  -0.048300
40            01     EEG T5   1.141489  1.183206  -0.041717
38            01     EEG T3   1.190670  1.230370  -0.039700
178           08    EEG Fp2   1.144509  1.179140  -0.034631
196           09     EEG F7   1.158128  1.184147  -0.026018
48            02     EEG F4   1.189255  1.214668  -0.025413
87            04     EEG C4   1.095301  1.118798  -0.023497
94            04    EEG Fp2   1.104804  1.125741  -0.020937

### Veo el csv

In [20]:
info_sujetos = pd.read_csv("C:\\Users\\yamal\\OneDrive\\Escritorio\\Proyectos en github\\Fractals-dimension-eeg\\eeg-during-mental-arithmetic-tasks-1.0.0\\eeg-during-mental-arithmetic-tasks-1.0.0\\subject-info.csv")

In [21]:
info_sujetos.head()

,Subject,Age,Gender,Recording year,Number of subtractions,Count quality
0,Subject00,21,F,2011,9.70,0
1,Subject01,18,F,2011,29.35,1
2,Subject02,19,F,2012,12.88,1
3,Subject03,17,F,2010,31.00,1
4,Subject04,17,F,2010,8.60,0

In [22]:
info_sujetos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Subject                 36 non-null     object
 1   Age                     36 non-null     int64
 2   Gender                  36 non-null     object
 3   Recording year          36 non-null     int64
 4   Number of subtractions  36 non-null     float64
 5   Count quality           36 non-null     int64
dtypes: float64(1), int64(3), object(2)
memory usage: 1.8+ KB

In [23]:
info_sujetos.describe()

             Age  Recording year  Number of subtractions  Count quality
count  36.000000       36.000000               36.000000      36.000000
mean   18.250000     2010.611111               17.612222       0.722222
std     2.169595        0.802773                9.694809       0.454257
min    16.000000     2010.000000                1.000000       0.000000
25%    17.000000     2010.000000                9.925000       0.000000
50%    17.000000     2010.000000               16.000000       1.000000
75%    19.000000     2011.000000               26.520000       1.000000
max    26.000000     2012.000000               34.590000       1.000000

In [24]:
info_sujetos.drop("Recording year",axis=1, inplace=True)

In [25]:
info_sujetos.head()

     Subject  Age Gender  Number of subtractions  Count quality
0  Subject00   21      F                    9.70              0
1  Subject01   18      F                   29.35              1
2  Subject02   19      F                   12.88              1
3  Subject03   17      F                   31.00              1
4  Subject04   17      F                    8.60              0

In [26]:
info_sujetos.groupby("Count quality").count()

               Subject  Age  Gender  Number of subtractions
Count quality
0                   10   10      10                      10
1                   26   26      26                      26

In [27]:
info_sujetos.groupby(["Gender", "Count quality"]).size()

Gender  Count quality
F       0                 7
        1                20
M       0                 3
        1                 6
dtype: int64

### DF fraccionado

In [28]:
def leer_edf(path):
    raw = mne.io.read_raw_edf(path, preload=True, verbose=False)
    data = raw.get_data()
    chans = raw.ch_names
    sfreq = raw.info['sfreq']
    return data, chans, sfreq

In [29]:
"""
Recibe: información de un canal.
Retorna: La información del canal dividida en 9 segmentos de 20 segundos
"""


def dividir20(data , duracion, sfreq):
    duracion_bloque = 20  # segundos
    muestras_bloque = int(sfreq * duracion_bloque)


    bloques_20 = []
    for i in range(int(duracion/duracion_bloque)):
        start = i * muestras_bloque
        end = start + muestras_bloque
        bloque = data[start:end]
        bloques_20.append(bloque)

    return bloques_20

In [30]:
"""
Recorro cada canal y a cada uno le aplico la función de dividirlo en bloques de 20 segundos.
Crea un diccionario de listas cuya clave es cada canal y sus valores los bloques temporales.
"""

def DividirPorCanal(data_sujeto, sfreq, chans):
    diccionario_canales = {}
    for canal, data_canal in enumerate(data_sujeto):
        division_canal = dividir20(data_canal, data_sujeto.shape[1]/sfreq, sfreq)
        diccionario_canales[chans[canal]]=division_canal

    return diccionario_canales

In [31]:
"""
En la libreria Antropy existe la funcion de Higuchi para df, usaré esa misma
Hago una funcion que calcula la df por canal y por bloque de 20 seg.

Tengo 9 dimensiones fractales por canal, voy a sacar el promedio.
hicimos 9 bloques de 20 segundos para que el resultado sea mas acertado. Calcular dm en bloques 
muy grandes de tiempo no es recomendable
"""

def FDPorCanal (diccionario_canales):
    diccionario_df = {}
    diccionario_promedio = {}
    for canal in diccionario_canales:
        listaDF_canal = []
        for i in diccionario_canales[canal]:
           fd_higuchi= ant.higuchi_fd(i, kmax = 10)
           listaDF_canal.append(fd_higuchi)
        diccionario_df[canal] = listaDF_canal.copy()
        diccionario_promedio[canal] = sum(listaDF_canal)/len(listaDF_canal)


    return diccionario_promedio

In [32]:
#Hago todo el proceso de calcular df en una sola función para aplicar por .edf. l uego automatizo
def CalculoDF(path):
    data, chans, sfreq = leer_edf(path)
    diccionario_canales = DividirPorCanal(data, sfreq, chans)
    diccionario_promedio = FDPorCanal(diccionario_canales)

    return diccionario_promedio

In [33]:
CalculoDF("C:\\Users\\yamal\\OneDrive\\Escritorio\\Proyectos en github\\Fractals-dimension-eeg\\eeg-during-mental-arithmetic-tasks-1.0.0\\eeg-during-mental-arithmetic-tasks-1.0.0\\Subject00_1.edf")

{'EEG Fp1': 1.1026697167219437,
 'EEG Fp2': 1.1197299952555118,
 'EEG F3': 1.1023168695391117,
 'EEG F4': 1.097645296425881,
 'EEG F7': 1.1245940331192672,
 'EEG F8': 1.123973039934177,
 'EEG T3': 1.106592869123511,
 'EEG T4': 1.0939193767175963,
 'EEG C3': 1.1040681865520763,
 'EEG C4': 1.1014770461326568,
 'EEG T5': 1.0963556405576853,
 'EEG T6': 1.0844444649099594,
 'EEG P3': 1.0928653997554731,
 'EEG P4': 1.0813178565008126,
 'EEG O1': 1.088543072829842,
 'EEG O2': 1.0696603841278245,
 'EEG Fz': 1.0970443525125064,
 'EEG Cz': 1.1001175981758557,
 'EEG Pz': 1.0915019734261662,
 'EEG A2-A1': 1.0846257754778854,
 'ECG ECG': 1.059151792969644}

In [34]:
mainPath = "C:\\Users\\yamal\\OneDrive\\Escritorio\\Proyectos en github\\Fractals-dimension-eeg\\eeg-during-mental-arithmetic-tasks-1.0.0\\eeg-during-mental-arithmetic-tasks-1.0.0"
result = []
for file in os.listdir(mainPath):
    if file.startswith("Subject") and file.endswith(".edf"):
        filePath = os.path.join(mainPath, file)
        df_Subject = CalculoDF(filePath)
        df_Subject["Sujeto"] = file
        result.append(df_Subject)
df_resultado = pd.DataFrame(result)
df_resultado.set_index("Sujeto", inplace=True)
print (df_resultado.head(2))

                  EEG Fp1  EEG Fp2    EEG F3    EEG F4    EEG F7    EEG F8  \
Sujeto
Subject00_1.edf  1.102670  1.11973  1.102317  1.097645  1.124594  1.123973
Subject00_2.edf  1.134732  1.13094  1.111707  1.105077  1.144263  1.147398

                   EEG T3    EEG T4    EEG C3    EEG C4  ...    EEG T6  \
Sujeto                                                   ...
Subject00_1.edf  1.106593  1.093919  1.104068  1.101477  ...  1.084444
Subject00_2.edf  1.124691  1.112482  1.110506  1.108315  ...  1.105374

                   EEG P3    EEG P4    EEG O1    EEG O2    EEG Fz    EEG Cz  \
Sujeto
Subject00_1.edf  1.092865  1.081318  1.088543  1.069660  1.097044  1.100118
Subject00_2.edf  1.115240  1.104324  1.101014  1.081384  1.103726  1.104388

                   EEG Pz  EEG A2-A1   ECG ECG
Sujeto
Subject00_1.edf  1.091502   1.084626  1.059152
Subject00_2.edf  1.117280   1.159927  1.074017

[2 rows x 21 columns]

In [35]:
#Para que no corte al imprimir el df
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)
print(df_resultado)

                  EEG Fp1   EEG Fp2    EEG F3    EEG F4    EEG F7    EEG F8  \
Sujeto
Subject00_1.edf  1.102670  1.119730  1.102317  1.097645  1.124594  1.123973
Subject00_2.edf  1.134732  1.130940  1.111707  1.105077  1.144263  1.147398
Subject01_1.edf  1.145034  1.146002  1.140149  1.126669  1.151928  1.140875
Subject01_2.edf  1.175808  1.168565  1.136131  1.140059  1.156185  1.160347
Subject02_1.edf  1.265691  1.170144  1.165206  1.215721  1.260586  1.244903
Subject02_2.edf  1.272918  1.214251  1.194197  1.189885  1.273985  1.239024
Subject03_1.edf  1.123835  1.117084  1.088036  1.087552  1.116321  1.101685
Subject03_2.edf  1.147961  1.154362  1.107989  1.103213  1.124487  1.119959
Subject04_1.edf  1.113540  1.124073  1.110060  1.110950  1.110502  1.118236
Subject04_2.edf  1.114715  1.105356  1.102425  1.098530  1.117504  1.105082
Subject05_1.edf  1.134807  1.173265  1.108969  1.103107  1.124087  1.141224
Subject05_2.edf  1.190881  1.162541  1.123249  1.128767  1.157259  1.148963
Subject06_1.edf  1.135773  1.136688  1.137365  1.127202  1.146677  1.128363
Subject06_2.edf  1.192072  1.209163  1.205569  1.176733  1.205057  1.190792
Subject07_1.edf  1.199330  1.196440  1.159654  1.159937  1.186234  1.200816
Subject07_2.edf  1.186041  1.221055  1.195988  1.204054  1.207295  1.277989
Subject08_1.edf  1.143803  1.179716  1.105847  1.116243  1.118239  1.145444
Subject08_2.edf  1.142141  1.144406  1.120564  1.129679  1.135466  1.138372
Subject09_1.edf  1.174616  1.149624  1.102834  1.098724  1.182812  1.149387
Subject09_2.edf  1.199072  1.190513  1.141041  1.133598  1.158791  1.164026
Subject10_1.edf  1.143231  1.146169  1.135181  1.147955  1.148666  1.157884
Subject10_2.edf  1.164763  1.164056  1.142906  1.157032  1.166171  1.151495
Subject11_1.edf  1.195149  1.222167  1.157986  1.154284  1.160203  1.163190
Subject11_2.edf  1.303928  1.339175  1.210430  1.213360  1.202247  1.267934
Subject12_1.edf  1.203051  1.206688  1.159824  1.118664  1.215697  1.211591
Subject12_2.edf  1.231857  1.197510  1.170156  1.141885  1.234353  1.198710
Subject13_1.edf  1.180401  1.189886  1.169112  1.181308  1.161185  1.219758
Subject13_2.edf  1.139818  1.128477  1.124731  1.126193  1.123150  1.130481
Subject14_1.edf  1.238463  1.160620  1.119597  1.126795  1.168166  1.162608
Subject14_2.edf  1.194386  1.150046  1.131297  1.125423  1.150438  1.153503
Subject15_1.edf  1.098404  1.098322  1.092315  1.086960  1.123947  1.110710
Subject15_2.edf  1.116481  1.122468  1.102426  1.103545  1.140056  1.126394
Subject16_1.edf  1.136875  1.135120  1.129826  1.138034  1.146355  1.160065
Subject16_2.edf  1.217123  1.236386  1.215307  1.231460  1.257430  1.236428
Subject17_1.edf  1.190444  1.265191  1.169292  1.155548  1.193420  1.191422
Subject17_2.edf  1.168707  1.219147  1.155152  1.136318  1.181246  1.167578
Subject18_1.edf  1.144108  1.124134  1.120946  1.132383  1.148543  1.132830
Subject18_2.edf  1.165351  1.164244  1.148269  1.151099  1.174673  1.135758
Subject19_1.edf  1.133883  1.137010  1.117571  1.124994  1.135974  1.130511
Subject19_2.edf  1.210319  1.246395  1.161171  1.180656  1.175970  1.288133
Subject20_1.edf  1.148322  1.179869  1.130168  1.137332  1.175370  1.181917
Subject20_2.edf  1.214360  1.186873  1.127787  1.126959  1.205164  1.194035
Subject21_1.edf  1.112791  1.134998  1.106068  1.108521  1.137559  1.134925
Subject21_2.edf  1.129437  1.139291  1.110210  1.131594  1.116185  1.140516
Subject22_1.edf  1.119674  1.114426  1.107341  1.082540  1.116346  1.125054
Subject22_2.edf  1.133520  1.129242  1.107827  1.096004  1.126677  1.129515
Subject23_1.edf  1.086274  1.135880  1.091481  1.085403  1.070995  1.109236
Subject23_2.edf  1.089290  1.161850  1.091217  1.091180  1.089921  1.124022
Subject24_1.edf  1.155321  1.157591  1.136438  1.133517  1.158259  1.152806
Subject24_2.edf  1.201516  1.219400  1.182347  1.179497  1.195029  1.199855
Subject25_1.edf  1.124640  1.104936  1.097035  1.091082  1.175367  1.144156
Subject25_2.edf  1.103723  1.090792  1.088489  1.081192  1.138030  1.126992
Subject26_1.edf  1.138745  1.135339  1.104569  1.109044  1.133897  1.116942
Subject26_2.edf  1.141558  1.128054  1.116691  1.132882  1.137004  1.128904
Subject27_1.edf  1.143669  1.186579  1.107284  1.123123  1.142762  1.181237
Subject27_2.edf  1.215303  1.263434  1.148050  1.172558  1.207259  1.264745
Subject28_1.edf  1.109233  1.105599  1.107253  1.108759  1.099492  1.123881
Subject28_2.edf  1.151756  1.147346  1.115031  1.123831  1.178121  1.137124
Subject29_1.edf  1.109349  1.108832  1.089941  1.093760  1.113046  1.117412
Subject29_2.edf  1.184761  1.181718  1.112166  1.116640  1.153967  1.150095
Subject30_1.edf  1.124814  1.131221  1.119358  1.117879  1.127400  1.138448
Subject30_2.edf  1.130007  1.137278  1.129533  1.130819  1.133355  1.135609
Subject31_1.edf  1.199980  1.156414  1.140086  1.137483  1.156858  1.158551
Subject31_2.edf  1.214700  1.165893  1.179993  1.156628  1.218702  1.187297
Subject32_1.edf  1.101701  1.098521  1.090279  1.090579  1.112865  1.116515
Subject32_2.edf  1.164188  1.142781  1.134337  1.120926  1.172797  1.171155
Subject33_1.edf  1.112279  1.105848  1.098851  1.096653  1.113932  1.105095
Subject33_2.edf  1.136129  1.155219  1.120862  1.120977  1.145864  1.150921
Subject34_1.edf  1.130649  1.148522  1.112826  1.111729  1.128381  1.131330
Subject34_2.edf  1.159042  1.168247  1.125209  1.126513  1.146685  1.147620
Subject35_1.edf  1.154923  1.173648  1.155966  1.160974  1.173376  1.174134
Subject35_2.edf  1.229723  1.219256  1.215879  1.199332  1.235690  1.222459

                   EEG T3    EEG T4    EEG C3    EEG C4    EEG T5    EEG T6  \
Sujeto
Subject00_1.edf  1.106593  1.093919  1.104068  1.101477  1.096356  1.084444
Subject00_2.edf  1.124691  1.112482  1.110506  1.108315  1.121802  1.105374
Subject01_1.edf  1.214111  1.135839  1.146670  1.123640  1.175700  1.142716
Subject01_2.edf  1.191241  1.151814  1.137061  1.137274  1.142048  1.156093
Subject02_1.edf  1.186070  1.174058  1.148902  1.145250  1.172746  1.153915
Subject02_2.edf  1.235584  1.211102  1.162687  1.147880  1.240693  1.227608
Subject03_1.edf  1.097741  1.099486  1.084828  1.082667  1.092446  1.080142
Subject03_2.edf  1.115791  1.116144  1.092602  1.090677  1.120512  1.090492
Subject04_1.edf  1.118649  1.111812  1.112747  1.120142  1.115866  1.101056
Subject04_2.edf  1.104439  1.105375  1.098263  1.095994  1.110859  1.095607
Subject05_1.edf  1.116841  1.109451  1.103971  1.094075  1.167704  1.094491
Subject05_2.edf  1.133788  1.146566  1.129390  1.123267  1.173860  1.113528
Subject06_1.edf  1.137716  1.109959  1.127683  1.114759  1.169395  1.106637
Subject06_2.edf  1.223297  1.204162  1.198121  1.198879  1.284055  1.192003
Subject07_1.edf  1.134791  1.165047  1.132765  1.117572  1.158279  1.130420
Subject07_2.edf  1.182800  1.222412  1.168867  1.150915  1.197417  1.167745
Subject08_1.edf  1.116079  1.111178  1.103431  1.106784  1.111806  1.108180
Subject08_2.edf  1.140048  1.134428  1.122674  1.122542  1.133289  1.132456
Subject09_1.edf  1.127139  1.115030  1.095345  1.088701  1.129142  1.112060
Subject09_2.edf  1.177859  1.156317  1.130176  1.123442  1.174127  1.157413
Subject10_1.edf  1.132923  1.133780  1.129212  1.121154  1.145267  1.138872
Subject10_2.edf  1.133530  1.122794  1.110084  1.112773  1.135919  1.114152
Subject11_1.edf  1.163782  1.166091  1.157486  1.153547  1.170547  1.159473
Subject11_2.edf  1.186473  1.215567  1.194087  1.237506  1.219206  1.219438
Subject12_1.edf  1.157713  1.147655  1.123083  1.116923  1.172858  1.115691
Subject12_2.edf  1.161312  1.116729  1.117118  1.099390  1.164537  1.090497
Subject13_1.edf  1.175665  1.188245  1.159250  1.215356  1.208108  1.254588
Subject13_2.edf  1.130872  1.126924  1.118996  1.119886  1.149925  1.136096
Subject14_1.edf  1.145966  1.139599  1.125497  1.135377  1.150663  1.120197
Subject14_2.edf  1.149611  1.122430  1.138200  1.140024  1.153995  1.119007
Subject15_1.edf  1.082093  1.097753  1.080780  1.082883  1.081511  1.077529
Subject15_2.edf  1.113326  1.118187  1.107337  1.103436  1.109660  1.098534
Subject16_1.edf  1.134806  1.189013  1.121528  1.124449  1.131582  1.184526
Subject16_2.edf  1.275218  1.309225  1.197481  1.201652  1.212130  1.303694
Subject17_1.edf  1.176534  1.162761  1.151933  1.153335  1.174998  1.121222
Subject17_2.edf  1.181297  1.144098  1.146805  1.153947  1.213867  1.100976
Subject18_1.edf  1.133387  1.116505  1.112850  1.109583  1.146346  1.134912
Subject18_2.edf  1.154803  1.147533  1.119530  1.150980  1.208131  1.195628
Subject19_1.edf  1.108102  1.152508  1.103287  1.113997  1.102550  1.087992
Subject19_2.edf  1.163767  1.320151  1.153883  1.182905  1.163342  1.145843
Subject20_1.edf  1.085145  1.115835  1.120675  1.105159  1.105023  1.098483
Subject20_2.edf  1.089444  1.141317  1.124528  1.123544  1.102432  1.131752
Subject21_1.edf  1.111219  1.108039  1.105580  1.104978  1.122126  1.113509
Subject21_2.edf  1.113015  1.116138  1.115187  1.115574  1.106736  1.124542
Subject22_1.edf  1.108571  1.096075  1.102744  1.101787  1.110216  1.103272
Subject22_2.edf  1.130339  1.159858  1.113701  1.111603  1.148599  1.116445
Subject23_1.edf  1.081216  1.134439  1.079752  1.081503  1.075844  1.074629
Subject23_2.edf  1.092778  1.146978  1.094431  1.094071  1.090479  1.115386
Subject24_1.edf  1.139574  1.141721  1.122935  1.121709  1.138411  1.129448
Subject24_2.edf  1.185982  1.205831  1.166198  1.172653  1.193233  1.175869
Subject25_1.edf  1.091671  1.125363  1.064400  1.065206  1.077296  1.083774
Subject25_2.edf  1.088902  1.130939  1.064337  1.059760  1.071716  1.084803
Subject26_1.edf  1.114440  1.105400  1.099968  1.098876  1.093457  1.095998
Subject26_2.edf  1.122064  1.125588  1.114298  1.108191  1.110258  1.113787
Subject27_1.edf  1.120186  1.148258  1.113640  1.117738  1.128956  1.125597
Subject27_2.edf  1.167823  1.210369  1.156908  1.164658  1.198789  1.187773
Subject28_1.edf  1.099144  1.107074  1.104635  1.102470  1.094898  1.101151
Subject28_2.edf  1.137132  1.124268  1.112533  1.113277  1.122061  1.130830
Subject29_1.edf  1.085438  1.083897  1.087157  1.083726  1.085333  1.062258
Subject29_2.edf  1.111403  1.109450  1.102747  1.095674  1.099185  1.076203
Subject30_1.edf  1.124931  1.119379  1.093661  1.103201  1.121866  1.141415
Subject30_2.edf  1.126740  1.129572  1.101645  1.124199  1.144872  1.161053
Subject31_1.edf  1.137415  1.123961  1.129493  1.133409  1.139646  1.136116
Subject31_2.edf  1.181234  1.167762  1.138939  1.141546  1.174098  1.190396
Subject32_1.edf  1.089651  1.078448  1.086630  1.085709  1.107537  1.068917
Subject32_2.edf  1.149777  1.131108  1.124192  1.108733  1.162468  1.089866
Subject33_1.edf  1.102636  1.099093  1.090441  1.095420  1.090182  1.066124
Subject33_2.edf  1.147109  1.131454  1.123417  1.123150  1.153756  1.109062
Subject34_1.edf  1.091781  1.113001  1.109781  1.108790  1.099256  1.118384
Subject34_2.edf  1.101401  1.130338  1.126662  1.128074  1.115316  1.136837
Subject35_1.edf  1.144595  1.174860  1.165595  1.166852  1.181048  1.162400
Subject35_2.edf  1.237069  1.220455  1.228081  1.220155  1.231649  1.207843

                   EEG P3    EEG P4    EEG O1    EEG O2    EEG Fz    EEG Cz  \
Sujeto
Subject00_1.edf  1.092865  1.081318  1.088543  1.069660  1.097044  1.100118
Subject00_2.edf  1.115240  1.104324  1.101014  1.081384  1.103726  1.104388
Subject01_1.edf  1.133040  1.111759  1.114661  1.106116  1.125265  1.127634
Subject01_2.edf  1.129328  1.131255  1.143568  1.127241  1.126794  1.132375
Subject02_1.edf  1.142115  1.127567  1.156038  1.113329  1.139645  1.140658
Subject02_2.edf  1.146137  1.131767  1.162774  1.123581  1.158453  1.144973
Subject03_1.edf  1.077070  1.072430  1.061823  1.072036  1.086223  1.072334
Subject03_2.edf  1.097052  1.102508  1.086943  1.094746  1.107956  1.100222
Subject04_1.edf  1.105159  1.097761  1.102963  1.100754  1.112396  1.116999
Subject04_2.edf  1.090393  1.090811  1.095715  1.096772  1.096633  1.097993
Subject05_1.edf  1.079415  1.072179  1.060406  1.058434  1.110163  1.097749
Subject05_2.edf  1.107378  1.097304  1.065996  1.060354  1.133980  1.134026
Subject06_1.edf  1.141380  1.105253  1.200352  1.132824  1.127977  1.122474
Subject06_2.edf  1.230467  1.209556  1.264881  1.206034  1.180725  1.194126
Subject07_1.edf  1.098563  1.102360  1.107725  1.108345  1.123455  1.107921
Subject07_2.edf  1.129713  1.140023  1.131518  1.139004  1.158909  1.139789
Subject08_1.edf  1.091931  1.092652  1.082470  1.084654  1.101624  1.103807
Subject08_2.edf  1.116154  1.109630  1.104747  1.100439  1.115665  1.116680
Subject09_1.edf  1.100430  1.085078  1.093157  1.083976  1.090258  1.086342
Subject09_2.edf  1.138963  1.120401  1.134855  1.124892  1.122941  1.122983
Subject10_1.edf  1.121843  1.111317  1.116778  1.107053  1.129394  1.127876
Subject10_2.edf  1.082286  1.074637  1.072454  1.067585  1.125561  1.119656
Subject11_1.edf  1.153080  1.146614  1.142447  1.145217  1.156091  1.157268
Subject11_2.edf  1.208437  1.199042  1.208289  1.213991  1.203674  1.212124
Subject12_1.edf  1.116647  1.107366  1.090955  1.093963  1.141039  1.118720
Subject12_2.edf  1.082745  1.071328  1.052063  1.058490  1.154076  1.113560
Subject13_1.edf  1.197425  1.159312  1.175803  1.220105  1.160649  1.162896
Subject13_2.edf  1.134659  1.123012  1.129410  1.143352  1.120832  1.115820
Subject14_1.edf  1.105993  1.115835  1.108160  1.112231  1.120975  1.136248
Subject14_2.edf  1.123871  1.113900  1.128977  1.130603  1.129527  1.147204
Subject15_1.edf  1.059671  1.058323  1.055760  1.057350  1.085676  1.084705
Subject15_2.edf  1.082866  1.083833  1.083093  1.078669  1.101787  1.102652
Subject16_1.edf  1.105663  1.100527  1.084123  1.085217  1.128812  1.126118
Subject16_2.edf  1.164267  1.164694  1.137636  1.132114  1.191868  1.180406
Subject17_1.edf  1.137289  1.130454  1.110893  1.116262  1.151916  1.150666
Subject17_2.edf  1.148467  1.128966  1.117031  1.125497  1.132294  1.139371
Subject18_1.edf  1.112569  1.104516  1.111176  1.106700  1.134732  1.116918
Subject18_2.edf  1.147282  1.162851  1.166218  1.164309  1.162219  1.149960
Subject19_1.edf  1.069561  1.074339  1.074110  1.081695  1.118988  1.124956
Subject19_2.edf  1.127235  1.130364  1.136669  1.154063  1.162644  1.156242
Subject20_1.edf  1.095251  1.087560  1.086810  1.083322  1.119171  1.101978
Subject20_2.edf  1.116843  1.118013  1.116750  1.115834  1.103814  1.120064
Subject21_1.edf  1.099953  1.103645  1.086824  1.089053  1.112118  1.108519
Subject21_2.edf  1.107840  1.121548  1.086115  1.093607  1.125144  1.119620
Subject22_1.edf  1.091370  1.087181  1.065966  1.076575  1.106231  1.105898
Subject22_2.edf  1.120043  1.111633  1.106391  1.098487  1.105970  1.110635
Subject23_1.edf  1.066099  1.066374  1.050287  1.050334  1.081047  1.080564
Subject23_2.edf  1.083147  1.083228  1.059932  1.057776  1.088095  1.093232
Subject24_1.edf  1.098192  1.088311  1.091410  1.079404  1.136082  1.122711
Subject24_2.edf  1.134949  1.105722  1.148133  1.092434  1.185731  1.174015
Subject25_1.edf  1.049534  1.050086  1.065632  1.059412  1.084812  1.062874
Subject25_2.edf  1.049627  1.048461  1.064172  1.054455  1.078883  1.061589
Subject26_1.edf  1.071471  1.077352  1.056932  1.058051  1.104787  1.099082
Subject26_2.edf  1.095466  1.103059  1.071967  1.071088  1.116113  1.112310
Subject27_1.edf  1.112865  1.107785  1.089311  1.084548  1.105525  1.114516
Subject27_2.edf  1.161897  1.177454  1.154471  1.147275  1.135725  1.153752
Subject28_1.edf  1.089469  1.085995  1.079397  1.066669  1.107587  1.114835
Subject28_2.edf  1.111601  1.109072  1.109673  1.089029  1.123487  1.115925
Subject29_1.edf  1.064243  1.061375  1.053745  1.051290  1.086836  1.084794
Subject29_2.edf  1.074246  1.067989  1.060620  1.058492  1.109527  1.097494
Subject30_1.edf  1.080626  1.069463  1.079400  1.070948  1.120909  1.107239
Subject30_2.edf  1.094833  1.093727  1.107102  1.085864  1.130745  1.119848
Subject31_1.edf  1.122891  1.120844  1.107904  1.096074  1.136456  1.134799
Subject31_2.edf  1.149142  1.144791  1.154405  1.129918  1.148765  1.139606
Subject32_1.edf  1.099900  1.082154  1.172308  1.143100  1.088111  1.091761
Subject32_2.edf  1.139344  1.110909  1.232963  1.192935  1.117518  1.111040
Subject33_1.edf  1.064205  1.060782  1.053418  1.058353  1.095644  1.096893
Subject33_2.edf  1.117510  1.102705  1.098853  1.098841  1.120247  1.129825
Subject34_1.edf  1.092866  1.104657  1.110563  1.169318  1.112412  1.116464
Subject34_2.edf  1.120764  1.132098  1.145221  1.208284  1.126745  1.138354
Subject35_1.edf  1.155426  1.154982  1.131363  1.135079  1.158913  1.166565
Subject35_2.edf  1.220300  1.217953  1.204622  1.204385  1.186842  1.215333

                   EEG Pz  EEG A2-A1   ECG ECG
Sujeto
Subject00_1.edf  1.091502   1.084626  1.059152
Subject00_2.edf  1.117280   1.159927  1.074017
Subject01_1.edf  1.113762   1.221734  1.152094
Subject01_2.edf  1.150439   1.231467  1.241033
Subject02_1.edf  1.135152   1.219417  1.247263
Subject02_2.edf  1.134122   1.224961  1.198445
Subject03_1.edf  1.062321   1.107037  1.149084
Subject03_2.edf  1.072868   1.124959  1.170886
Subject04_1.edf  1.101920   1.123588  1.158235
Subject04_2.edf  1.096610   1.142960  1.104180
Subject05_1.edf  1.078036   1.118338  1.082700
Subject05_2.edf  1.103307   1.204180  1.077484
Subject06_1.edf  1.119056   1.161083  1.124209
Subject06_2.edf  1.210896   1.193114  1.145092
Subject07_1.edf  1.088003   1.242045  1.189930
Subject07_2.edf  1.125134   1.244717  1.204794
Subject08_1.edf  1.088721   1.178891  1.064412
Subject08_2.edf  1.109959   1.106546  1.061300
Subject09_1.edf  1.080963   1.181038  1.099699
Subject09_2.edf  1.118648   1.184044  1.097274
Subject10_1.edf  1.112763   1.177177  1.077735
Subject10_2.edf  1.077711   1.150697  1.079050
Subject11_1.edf  1.148031   1.158136  1.126609
Subject11_2.edf  1.205025   1.245576  1.193977
Subject12_1.edf  1.097848   1.256844  1.098441
Subject12_2.edf  1.062673   1.269851  1.111789
Subject13_1.edf  1.156333   1.238567  1.238036
Subject13_2.edf  1.123877   1.168927  1.158292
Subject14_1.edf  1.122463   1.118582  1.194438
Subject14_2.edf  1.132646   1.241448  1.190565
Subject15_1.edf  1.058123   1.156895  1.064926
Subject15_2.edf  1.084051   1.191757  1.092300
Subject16_1.edf  1.100034   1.184792  1.075345
Subject16_2.edf  1.152278   1.243705  1.081127
Subject17_1.edf  1.143339   1.291428  1.094738
Subject17_2.edf  1.146578   1.266417  1.081962
Subject18_1.edf  1.107007   1.133993  1.090899
Subject18_2.edf  1.157032   1.199561  1.099587
Subject19_1.edf  1.072039   1.195753  1.150737
Subject19_2.edf  1.134705   1.243325  1.158143
Subject20_1.edf  1.104654   1.218014  1.105825
Subject20_2.edf  1.139975   1.217092  1.133225
Subject21_1.edf  1.104856   1.110076  1.086331
Subject21_2.edf  1.122284   1.125083  1.093992
Subject22_1.edf  1.084089   1.122501  1.097260
Subject22_2.edf  1.108658   1.153224  1.096198
Subject23_1.edf  1.066751   1.107152  1.110160
Subject23_2.edf  1.080675   1.136030  1.119038
Subject24_1.edf  1.088972   1.236858  1.062128
Subject24_2.edf  1.118191   1.301012  1.070912
Subject25_1.edf  1.050171   1.178215  1.119160
Subject25_2.edf  1.050131   1.167420  1.110294
Subject26_1.edf  1.078605   1.137597  1.090870
Subject26_2.edf  1.108725   1.202192  1.097484
Subject27_1.edf  1.108444   1.170651  1.129907
Subject27_2.edf  1.161496   1.235284  1.124474
Subject28_1.edf  1.087150   1.125104  1.144949
Subject28_2.edf  1.110347   1.202195  1.155505
Subject29_1.edf  1.060809   1.116279  1.128621
Subject29_2.edf  1.065540   1.199868  1.168161
Subject30_1.edf  1.073057   1.149215  1.116460
Subject30_2.edf  1.097021   1.188763  1.119720
Subject31_1.edf  1.121880   1.262051  1.061039
Subject31_2.edf  1.153484   1.282861  1.104390
Subject32_1.edf  1.094212   1.138542  1.093643
Subject32_2.edf  1.121906   1.169112  1.109076
Subject33_1.edf  1.063392   1.120749  1.124249
Subject33_2.edf  1.112382   1.133638  1.139633
Subject34_1.edf  1.095502   1.193070  1.100887

#Ahora voy a calcular la media y dispersión de los sujetos en reposo por canal y en resolución de actividades. Esto es para tener una idea general de la variación por canales. Sin embargo, la hipótesis principal es que la dimensión fractal aumenta en aquellos que han resuelto erradamente.

In [36]:
canales = list(df_resultado.columns)
print(canales)

['EEG Fp1', 'EEG Fp2', 'EEG F3', 'EEG F4', 'EEG F7', 'EEG F8', 'EEG T3', 'EEG T4', 'EEG C3', 'EEG C4', 'EEG T5', 'EEG T6', 'EEG P3', 'EEG P4', 'EEG O1', 'EEG O2', 'EEG Fz', 'EEG Cz', 'EEG Pz', 'EEG A2-A1', 'ECG ECG']

In [37]:
df_reposo = df_resultado[df_resultado.index.str.contains("_1.edf")]

In [38]:
df_actividad = df_resultado[df_resultado.index.str.contains("_2.edf")]

In [39]:
df_reposo.describe()

,EEG Fp1,EEG Fp2,EEG F3,EEG F4,EEG F7,EEG F8,EEG T3,EEG T4,EEG C3,EEG C4,EEG T5,EEG T6,EEG P3,EEG P4,EEG O1,EEG O2,EEG Fz,EEG Cz,EEG Pz,EEG A2-A1,ECG ECG
count,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000
mean,1.146541,1.149342,1.121862,1.122196,1.146112,1.148531,1.124842,1.127626,1.113956,1.113839,1.129027,1.116404,1.102669,1.096264,1.097767,1.095207,1.116638,1.113664,1.097541,1.170200,1.117698
std,0.040343,0.037576,0.024976,0.029352,0.035507,0.034198,0.031551,0.029291,0.024515,0.028235,0.035292,0.037564,0.031222,0.026556,0.036517,0.035976,0.022374,0.024309,0.027406,0.052025,0.045866
min,1.086274,1.098322,1.088036,1.082540,1.070995,1.101685,1.081216,1.078448,1.064400,1.065206,1.075844,1.062258,1.049534,1.050086,1.050287,1.050334,1.081047,1.062874,1.050171,1.084626,1.059152
25%,1.118140,1.122987,1.104135,1.098454,1.122520,1.123950,1.101763,1.107798,1.098812,1.098012,1.098531,1.092866,1.080323,1.076599,1.072074,1.070626,1.100479,1.098749,1.078463,1.123316,1.089735
50%,1.137810,1.141506,1.115199,1.118271,1.144558,1.141049,1.119417,1.117942,1.111264,1.109187,1.125541,1.112784,1.099231,1.095207,1.090133,1.084935,1.115700,1.114675,1.094857,1.165867,1.107993
75%,1.160145,1.173361,1.138046,1.137370,1.162930,1.162754,1.138181,1.147805,1.128065,1.122192,1.160636,1.135213,1.117946,1.108668,1.110964,1.109316,1.130728,1.126497,1.113013,1.201318,1.133667
max,1.265691,1.265191,1.169292,1.215721,1.260586,1.244903,1.214111,1.189013,1.165595,1.215356,1.208108,1.254588,1.197425,1.159312,1.200352,1.220105,1.160649,1.166565,1.156333,1.291428,1.247263

In [40]:
df_actividad.describe()

,EEG Fp1,EEG Fp2,EEG F3,EEG F4,EEG F7,EEG F8,EEG T3,EEG T4,EEG C3,EEG C4,EEG T5,EEG T6,EEG P3,EEG P4,EEG O1,EEG O2,EEG Fz,EEG Cz,EEG Pz,EEG A2-A1,ECG ECG
count,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000
mean,1.174114,1.175159,1.141843,1.141225,1.169069,1.171090,1.151721,1.157941,1.132269,1.133515,1.157084,1.142073,1.125014,1.120516,1.123479,1.117273,1.133156,1.131589,1.122395,1.200897,1.126096
std,0.046707,0.049568,0.036709,0.036371,0.042458,0.049234,0.044288,0.052213,0.034153,0.038410,0.048200,0.049274,0.038938,0.038301,0.049502,0.046338,0.030505,0.032876,0.038710,0.053277,0.044576
min,1.089290,1.090792,1.088489,1.081192,1.089921,1.105082,1.088902,1.105375,1.064337,1.059760,1.071716,1.076203,1.049627,1.048461,1.052063,1.054455,1.078883,1.061589,1.050131,1.106546,1.061300
25%,1.138896,1.141909,1.114315,1.120964,1.137774,1.135721,1.120496,1.123899,1.112026,1.108628,1.119213,1.108140,1.096656,1.101207,1.086736,1.084744,1.114130,1.111993,1.101736,1.158252,1.095646
50%,1.167029,1.164150,1.130415,1.131206,1.158025,1.151208,1.143578,1.137873,1.123804,1.123354,1.151841,1.131291,1.120403,1.112766,1.116891,1.108136,1.126153,1.121524,1.120277,1.199714,1.111041
75%,1.203717,1.210435,1.163417,1.160914,1.202950,1.195204,1.181250,1.176862,1.148574,1.150931,1.194279,1.169776,1.141042,1.131850,1.145949,1.140091,1.155170,1.145530,1.141626,1.241918,1.158180
max,1.303928,1.339175,1.215879,1.231460,1.273985,1.288133,1.275218,1.320151,1.228081,1.237506,1.284055,1.303694,1.230467,1.217953,1.264881,1.213991,1.203674,1.215333,1.216861,1.328495,1.241033

In [41]:
#ahora con dos tablas separadas la actividad y el reposo, 
# haré una nueva columna con los sujetos asi puedo hacerlos coincidir luego.

#df_reposo

In [42]:
df_reposo["nombre"] = df_reposo.index.str[:9]

C:\Users\yamal\AppData\Local\Temp\ipykernel_59824\1744317788.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_reposo["nombre"] = df_reposo.index.str[:9]

In [43]:
df_actividad["nombre"] = df_actividad.index.str[:9]

C:\Users\yamal\AppData\Local\Temp\ipykernel_59824\2854395664.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_actividad["nombre"] = df_actividad.index.str[:9]

In [44]:
df_reposo = df_reposo.set_index("nombre")
df_actividad = df_actividad.set_index("nombre")

In [45]:
df_variacion = df_actividad - df_reposo

In [46]:
df_variacion

,EEG Fp1,EEG Fp2,EEG F3,EEG F4,EEG F7,EEG F8,EEG T3,EEG T4,EEG C3,EEG C4,EEG T5,EEG T6,EEG P3,EEG P4,EEG O1,EEG O2,EEG Fz,EEG Cz,EEG Pz,EEG A2-A1,ECG ECG
nombre,,,,,,,,,,,,,,,,,,,,,
Subject00,0.032063,0.011210,0.009390,0.007432,0.019669,0.023425,0.018098,0.018563,0.006437,0.006838,0.025447,0.020929,0.022374,0.023006,0.012471,0.011723,0.006682,0.004271,0.025778,0.075302,0.014865
Subject01,0.030775,0.022563,-0.004017,0.013390,0.004257,0.019472,-0.022871,0.015975,-0.009610,0.013635,-0.033652,0.013378,-0.003713,0.019496,0.028907,0.021124,0.001529,0.004742,0.036677,0.009733,0.088939
Subject02,0.007227,0.044106,0.028991,-0.025836,0.013400,-0.005878,0.049514,0.037043,0.013785,0.002631,0.067947,0.073694,0.004022,0.004200,0.006736,0.010253,0.018808,0.004314,-0.001030,0.005543,-0.048818
Subject03,0.024126,0.037278,0.019953,0.015661,0.008166,0.018274,0.018051,0.016659,0.007774,0.008010,0.028066,0.010349,0.019982,0.030078,0.025121,0.022710,0.021732,0.027888,0.010547,0.017922,0.021802
Subject04,0.001175,-0.018716,-0.007635,-0.012420,0.007002,-0.013154,-0.014209,-0.006437,-0.014484,-0.024148,-0.005006,-0.005450,-0.014766,-0.006950,-0.007248,-0.003982,-0.015764,-0.019005,-0.005310,0.019372,-0.054055
Subject05,0.056074,-0.010725,0.014279,0.025659,0.033172,0.007739,0.016947,0.037115,0.025419,0.029192,0.006155,0.019036,0.027962,0.025124,0.005590,0.001920,0.023817,0.036277,0.025271,0.085842,-0.005216
Subject06,0.056300,0.072474,0.068204,0.049531,0.058380,0.062429,0.085581,0.094203,0.070438,0.084120,0.114659,0.085365,0.089087,0.104303,0.064529,0.073210,0.052747,0.071652,0.091839,0.032031,0.020883
Subject07,-0.013290,0.024615,0.036334,0.044117,0.021062,0.077172,0.048009,0.057366,0.036103,0.033343,0.039138,0.037326,0.031150,0.037663,0.023793,0.030659,0.035454,0.031869,0.037131,0.002672,0.014864
Subject08,-0.001662,-0.035310,0.014718,0.013436,0.017227,-0.007072,0.023969,0.023250,0.019242,0.015757,0.021483,0.024276,0.024223,0.016978,0.022277,0.015785,0.014041,0.012872,0.021238,-0.072344,-0.003112
Subject09,0.024456,0.040888,0.038207,0.034874,-0.024021,0.014639,0.050720,0.041287,0.034831,0.034741,0.044985,0.045353,0.038532,0.035323,0.041698,0.040916,0.032684,0.036641,0.037685,0.003006,-0.002425
Subject10,0.021532,0.017886,0.007725,0.009077,0.017505,-0.006388,0.000606,-0.010987,-0.019128,-0.008381,-0.009348,-0.024719,-0.039557,-0.036679,-0.044324,-0.039468,-0.003833,-0.008220,-0.035053,-0.026479,0.001315
Subject11,0.108779,0.117008,0.052444,0.059076,0.042045,0.104744,0.022692,0.049476,0.036601,0.083960,0.048659,0.059965,0.055356,0.052428,0.065842,0.068774,0.047583,0.054856,0.056994,0.087440,0.067368
Subject12,0.028806,-0.009178,0.010332,0.023222,0.018656,-0.012881,0.003599,-0.030925,-0.005965,-0.017533,-0.008321,-0.025194,-0.033902,-0.036039,-0.038892,-0.035473,0.013036,-0.005160,-0.035176,0.013007,0.013347
Subject13,-0.040583,-0.061408,-0.044381,-0.055114,-0.038035,-0.089277,-0.044793,-0.061321,-0.040254,-0.095470,-0.058182,-0.118492,-0.062766,-0.036300,-0.046393,-0.076754,-0.039817,-0.047076,-0.032456,-0.069639,-0.079744
Subject14,-0.044077,-0.010574,0.011700,-0.001372,-0.017729,-0.009105,0.003645,-0.017169,0.012704,0.004647,0.003331,-0.001190,0.017877,-0.001935,0.020818,0.018372,0.008553,0.010956,0.010183,0.122866,-0.003873
Subject15,0.018077,0.024146,0.010111,0.016584,0.016110,0.015685,0.031234,0.020434,0.026557,0.020553,0.028149,0.021006,0.023196,0.025510,0.027333,0.021319,0.016111,0.017947,0.025928,0.034861,0.027374
Subject16,0.080248,0.101266,0.085482,0.093426,0.111075,0.076362,0.140412,0.120212,0.075953,0.077204,0.080549,0.119168,0.058604,0.064168,0.053513,0.046897,0.063055,0.054288,0.052244,0.058913,0.005782
Subject17,-0.021736,-0.046045,-0.014140,-0.019231,-0.012174,-0.023844,0.004763,-0.018663,-0.005128,0.000612,0.038869,-0.020245,0.011178,-0.001487,0.006138,0.009235,-0.019621,-0.011294,0.003239,-0.025011,-0.012776
Subject18,0.021244,0.040110,0.027323,0.018716,0.026130,0.002928,0.021416,0.031028,0.006679,0.041397,0.061785,0.060716,0.034713,0.058335,0.055041,0.057608,0.027488,0.033042,0.050025,0.065568,0.008688
Subject19,0.076436,0.109385,0.043600,0.055661,0.039997,0.157623,0.055664,0.167643,0.050595,0.068908,0.060793,0.057852,0.057674,0.056025,0.062559,0.072368,0.043655,0.031286,0.062666,0.047572,0.007406
Subject20,0.066038,0.007004,-0.002381,-0.010373,0.029794,0.012119,0.004299,0.025482,0.003853,0.018385,-0.002591,0.033269,0.021592,0.030453,0.029940,0.032512,-0.015358,0.018086,0.035321,-0.000922,0.027400
Subject21,0.016646,0.004294,0.004142,0.023073,-0.021374,0.005591,0.001796,0.008099,0.009607,0.010596,-0.015390,0.011034,0.007887,0.017902,-0.000710,0.004555,0.013027,0.011100,0.017427,0.015007,0.007661
Subject22,0.013846,0.014816,0.000486,0.013464,0.010332,0.004461,0.021768,0.063783,0.010957,0.009816,0.038384,0.013173,0.028673,0.024452,0.040425,0.021912,-0.000261,0.004737,0.024569,0.030723,-0.001062
Subject23,0.003016,0.025970,-0.000265,0.005777,0.018926,0.014787,0.011562,0.012539,0.014679,0.012568,0.014635,0.040756,0.017048,0.016854,0.009644,0.007442,0.007048,0.012667,0.013925,0.028878,0.008878
Subject24,0.046194,0.061809,0.045909,0.045980,0.036770,0.047050,0.046408,0.064109,0.043263,0.050944,0.054822,0.046421,0.036756,0.017411,0.056724,0.013030,0.049649,0.051304,0.029219,0.064155,0.008784
Subject25,-0.020917,-0.014144,-0.008547,-0.009890,-0.037337,-0.017165,-0.002769,0.005577,-0.000063,-0.005446,-0.005580,0.001029,0.000094,-0.001625,-0.001460,-0.004957,-0.005929,-0.001285,-0.000040,-0.010795,-0.008867
Subject26,0.002813,-0.007285,0.012122,0.023839,0.003108,0.011962,0.007624,0.020188,0.014330,0.009315,0.016801,0.017789,0.023995,0.025707,0.015035,0.013037,0.011326,0.013228,0.030120,0.064595,0.006615
Subject27,0.071634,0.076855,0.040766,0.049435,0.064496,0.083508,0.047637,0.062111,0.043268,0.046920,0.069833,0.062176,0.049031,0.069668,0.065160,0.062727,0.030200,0.039235,0.053052,0.064633,-0.005433
Subject28,0.042523,0.041747,0.007778,0.015072,0.078630,0.013243,0.037988,0.017194,0.007899,0.010807,0.027163,0.029679,0.022132,0.023076,0.030276,0.022359,0.015899,0.001090,0.023197,0.077091,0.010556
Subject29,0.075412,0.072886,0.022225,0.022881,0.040922,0.032683,0.025965,0.025553,0.015590,0.011948,0.013852,0.013945,0.010004,0.006614,0.006875,0.007202,0.022691,0.012700,0.004731,0.083588,0.039540
Subject30,0.005193,0.006057,0.010175,0.012940,0.005955,-0.002839,0.001808,0.010194,0.007985,0.020997,0.023006,0.019638,0.014207,0.024263,0.027702,0.014917,0.009837,0.012609,0.023965,0.039548,0.003260
Subject31,0.014720,0.009480,0.039907,0.019145,0.061844,0.028746,0.043820,0.043801,0.009446,0.008137,0.034453,0.054280,0.026251,0.023947,0.046501,0.033843,0.012309,0.004807,0.031603,0.020810,0.043352
Subject32,0.062487,0.044260,0.044058,0.030348,0.059932,0.054640,0.060126,0.052660,0.037562,0.023023,0.054931,0.020949,0.039444,0.028755,0.060655,0.049835,0.029406,0.019279,0.027694,0.030570,0.015432
Subject33,0.023850,0.049371,0.022011,0.024324,0.031932,0.045826,0.044473,0.032361,0.032976,0.027730,0.063574,0.042938,0.053304,0.041923,0.045435,0.040488,0.024603,0.032932,0.048990,0.012889,0.015383
Subject34,0.028393,0.019725,0.012383,0.014784,0.018304,0.016290,0.009619,0.017337,0.016882,0.019283,0.016060,0.018453,0.027897,0.027441,0.034658,0.038966,0.014333,0.021890,0.027212,-0.041189,-0.000590
Subject35,0.074800,0.045608,0.059913,0.038358,0.062314,0.048324,0.092475,0.045595,0.062486,0.053304,0.050601,0.045443,0.064873,0.062971,0.073260,0.069306,0.027930,0.048768,0.065346,0.137331,0.048809

In [47]:
df_variacion.describe()

,EEG Fp1,EEG Fp2,EEG F3,EEG F4,EEG F7,EEG F8,EEG T3,EEG T4,EEG C3,EEG C4,EEG T5,EEG T6,EEG P3,EEG P4,EEG O1,EEG O2,EEG Fz,EEG Cz,EEG Pz,EEG A2-A1,ECG ECG
count,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000
mean,0.027573,0.025818,0.019981,0.019029,0.022957,0.022559,0.026879,0.030315,0.018313,0.019676,0.028057,0.025669,0.022345,0.024252,0.025712,0.022066,0.016518,0.017925,0.024854,0.030697,0.008398
std,0.035353,0.040958,0.025407,0.026864,0.032088,0.042716,0.034267,0.041188,0.024600,0.032841,0.034204,0.039140,0.029489,0.029369,0.030438,0.031742,0.021399,0.023392,0.027351,0.047123,0.030134
min,-0.044077,-0.061408,-0.044381,-0.055114,-0.038035,-0.089277,-0.044793,-0.061321,-0.040254,-0.095470,-0.058182,-0.118492,-0.062766,-0.036679,-0.046393,-0.076754,-0.039817,-0.047076,-0.035176,-0.072344,-0.079744
25%,0.004648,0.001399,0.006829,0.008666,0.006740,-0.003599,0.004135,0.011952,0.006619,0.007717,0.005449,0.012638,0.010884,0.014294,0.006840,0.008787,0.006957,0.004631,0.010456,0.004909,-0.002597
50%,0.023988,0.023354,0.013331,0.017650,0.018791,0.014713,0.021592,0.024366,0.014057,0.014696,0.027615,0.020977,0.023595,0.024358,0.027517,0.021222,0.015116,0.013050,0.025853,0.029724,0.008175
75%,0.056130,0.044597,0.038632,0.031479,0.040228,0.046132,0.046715,0.046565,0.035149,0.033692,0.051656,0.045687,0.037200,0.035908,0.048254,0.040595,0.028299,0.032960,0.037270,0.064605,0.016795
max,0.108779,0.117008,0.085482,0.093426,0.111075,0.157623,0.140412,0.167643,0.075953,0.084120,0.114659,0.119168,0.089087,0.104303,0.073260,0.073210,0.063055,0.071652,0.091839,0.137331,0.088939

In [51]:
info_sujetos.head()

     Subject  Age Gender  Number of subtractions  Count quality
0  Subject00   21      F                    9.70              0
1  Subject01   18      F                   29.35              1
2  Subject02   19      F                   12.88              1
3  Subject03   17      F                   31.00              1
4  Subject04   17      F                    8.60              0

Ahora ya tenemos la variacion de la dimencion fractal entre estado reposo y resolución de ejercicios y tenemos ademas dos grupos de sujetos: los que aprobaron y los que no. Lo mas conveniente es usar una herramienta estadistica para comparar dos grupos independientes: prueba U de Mann–Whitney. Python tiene esta función.

Pruebo con Fp1 la prueba U

In [58]:
# Unimos las tablas por el nombre del sujeto
df = info_sujetos.merge(df_variacion, left_on='Subject', right_index=True)

# Separar ΔDF de Fp1 según grupo
grupo0 = df[df['Count quality'] == 0]['EEG Fp1']
grupo1 = df[df['Count quality'] == 1]['EEG Fp1']

In [59]:
u_stat, p_value = mannwhitneyu(grupo0, grupo1, alternative='two-sided')

In [60]:
print("Grupo 0 (no aprobaron) ΔDF Fp1:", grupo0.values)
print("Grupo 1 (aprobaron) ΔDF Fp1:", grupo1.values)
print("U-statistic:", u_stat)
print("p-value:", p_value)

Grupo 0 (no aprobaron) ΔDF Fp1: [ 0.03206269  0.00117512  0.05629986  0.02445592  0.02153204 -0.04407701
  0.07643624  0.01664593  0.01384621  0.00519272]
Grupo 1 (aprobaron) ΔDF Fp1: [ 0.03077472  0.00722701  0.02412571  0.05607391 -0.01328974 -0.00166182
  0.10877911  0.02880641 -0.0405826   0.01807707  0.0802482  -0.02173634
  0.02124354  0.06603761  0.0030157   0.0461944  -0.02091661  0.00281338
  0.07163359  0.04252301  0.07541165  0.0147205   0.06248692  0.02385043
  0.02839305  0.07480009]
U-statistic: 112.0
p-value: 0.5365259402507443

In [61]:
print("Media grupo0:", grupo0.mean())
print("Media grupo1:", grupo1.mean())

Media grupo0: 0.020356971707395276
Media grupo1: 0.03034803574076966

El cambio en Fp1 no parece depender del desempeño en matemática, según tus datos actuales. Ahora en todos los canales:

In [ ]:
canales = df_variacion.columns


resultados = {}


for canal in canales:
    grupo0 = df[df['Count quality'] == 0][canal]
    grupo1 = df[df['Count quality'] == 1][canal]
    

    u_stat, p_value = mannwhitneyu(grupo0, grupo1, alternative='two-sided')
    
   
    resultados[canal] = {
        'U-statistic': u_stat,
        'p-value': p_value,
        'mean_grupo0': grupo0.mean(),
        'mean_grupo1': grupo1.mean()
    }


df_resultados = pd.DataFrame(resultados).T
print(df_resultados)

           U-statistic   p-value  mean_grupo0  mean_grupo1
EEG Fp1          112.0  0.536526     0.020357     0.030348
EEG Fp2          112.0  0.536526     0.024772     0.026220
EEG F3           110.0  0.491004     0.018599     0.020512
EEG F4           117.0  0.658864     0.019226     0.018953
EEG F7            81.0  0.086722     0.009571     0.028105
EEG F8           107.0  0.426807     0.023668     0.022132
EEG T3           108.0  0.447644     0.022548     0.028545
EEG T4           119.0  0.710753     0.036918     0.027775
EEG C3           115.0  0.608568     0.016994     0.018820
EEG C4           115.0  0.608568     0.020813     0.019239
EEG T5           114.0  0.584078     0.028086     0.028046
EEG T6           102.0  0.331419     0.022199     0.027004
EEG P3           121.0  0.764019     0.022199     0.022401
EEG P4           114.0  0.584078     0.023971     0.024360
EEG O1           116.0  0.633504     0.021792     0.027220
EEG O2           122.0  0.791095     0.021452     0.022302
EEG Fz           105.0  0.386871     0.014733     0.017205
EEG Cz           102.0  0.331419     0.015602     0.018818
EEG Pz           119.0  0.710753     0.025375     0.024654
EEG A2-A1        141.0  0.710753     0.035895     0.028698
ECG ECG           91.0  0.173904    -0.000602     0.011860

ningún canal muestra diferencia estadísticamente significativa entre los grupos.